### PR TITLE
Update Godot to 4.2

### PR DESCRIPTION
**Pull request by Zishan-Rahman**

### CODE REVIEW

**Comment by Zishan-Rahman** [comment]
So the `aarch64` build succeeded, but [the `x86_64` builder couldn't delete the previous working directory](https://buildbot.flathub.org/#/builders/19/builds/10471). I'll summon Buildbot again, and hopefully this time the build will succeed.

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
The status was taking too long to get confirmed.

**Comment by Zishan-Rahman** [comment]
Status confirmation taking its time, eh?

I'll just wait this one out. Hopefully the status confirmation shows up once I wake up in the morning (it's 10 minutes to midnight in the UK as of the time I'm posting this comment).

**Comment by Zishan-Rahman** [comment]
bot, build

**Comment by Zishan-Rahman** [comment]
OK, so the status still isn't showing up here as confirmed, even though it should.

I'm going to try something different. I'm going to close this PR, then I will re-open it. Hopefully this triggers a test build and then its success shows up here.

**Comment by Zishan-Rahman** [comment]
Thank goodness, the status checks are now showing up here as having been confirmed. I can merge this PR once [the relevant PR for the _standard_ Godot Flatpak (_without_ C# support)](https://www.github.com/flathub/org.godotengine.Godot#147) gets merged as well :+1:

**Review by Calinou — APPROVED** [review]

**Pull request merged**
